### ISSUE TITLE
Settings not displayed correctly in backend

### ISSUE THREAD

**Issue by RadLikeWhoa** [coders-market/CM.Neos.ThemeModule#9]
Ever since updating to version 3.2.1, custom settings are not displayed correctly in the backend module. I can change colors, fonts, and text fields and the changes are compiled and persisted correctly, however, once I reload the page, all changes are gone and the default values are displayed again.

The exception to this are the text areas for custom SCSS and CSS code, which are unaffected by this.

**Comment by kdambekalns** [comment]
And it was working in 3.1.3, which you updated from?

**Comment by RadLikeWhoa** [comment]
Yes, it was. Downgrading the package back to 3.1.x makes it work again.
